---
# tasks file for role dmz

- name: Ensure ssh is enabled on port 22
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Port 22"
    line: "Port 22"
    insertafter: EOF
  notify: Restart sshd service

- name: Ensure ssh is enabled on port 6969
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Port 6969"
    line: "Port 6969"
    insertafter: "^Port 22"
  notify: Restart sshd service

- name: Copy login-notify script
  copy:
    src: etc/pam.d/login-notify.sh
    dest: /etc/pam.d/login-notify.sh
    owner: root
    group: root
    mode: "0700"
  register: result

- name: Enable login notification
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: "login-notify.sh"
    line: session optional pam_exec.so seteuid /etc/pam.d/login-notify.sh
  register: result
  when: result is changed
  notify: Restart sshd service

- name: Ensure fail2ban package is installed
  apt:
    name: fail2ban
    state: present

- name: Copy fail2ban configuration
  copy:
    src: etc/fail2ban/jail.conf.local
    dest: /etc/fail2ban/jail.conf.local
    owner: root
    group: root
    mode: "0700"
  register: result

- name: Ensure iptables-persistent package is installed
  apt:
    name: iptables-persistent
    state: present

- name: Ensure ipset package is installed
  apt:
    name: ipset
    state: present

- name: Add ipset restore service
  copy:
    src: etc/systemd/system/save-ipset-rules.service
    dest: /etc/systemd/system/save-ipset-rules.service
    owner: root
    group: root
    mode: "0777"
  register: result

- name: Copy ip blacklist configuration
  copy:
    src: etc/iptables/ipset
    dest: /etc/iptables/ipset
    owner: root
    group: root
    mode: "0777"
  register: result

- name: Enable INPUT traffic filtering
  iptables:
    chain: INPUT
    match: set
    match_set: blacklist
    match_set_flags: src
    jump: DROP

- name: Enable FORWARD traffic filtering
  iptables:
    chain: FORWARD
    match: set
    match_set: blacklist
    match_set_flags: src
    jump: DROP
