---
- name: rpi-ssh-login-notify playbook
  hosts: raspberrypi
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
  - name: Copy login-notify script
    copy:
      src: etc/pam.d/login-notify.sh
      dest: /etc/pam.d/login-notify.sh
      owner: root
      group: root
      mode: '0700'
    register: result

  - name: Enable login notification
    lineinfile:
      path: /etc/pam.d/sshd
      regexp: 'login-notify.sh'
      line: session optional pam_exec.so seteuid /etc/pam.d/login-notify.sh
