---
- name: rpi-nas playbook
  hosts: rpi-nas
  become: yes
  become_method: sudo

  tasks:
  - name: Ensure vim package is installed
    apt:
      name=vim
      state=present

  - name: Ensure screen package is installed
    apt:
      name=screen
      state=present

  - name: Ensure secure delete package is installed
    apt:
      name=secure-delete
      state=present

  - name: Ensure mc package is installed
    apt:
      name=mc
      state=present

  - name: Ensure autossh package is installed
    apt:
      name=autossh
      state=present

  - name: Ensure mdadm package is installed
    apt:
      name=mdadm
      state=present

  - name: Ensure samba package is installed
    apt:
      name=samba
      state=present

  - name: Ensure samba-common-bin package is installed
    apt:
      name=samba-common-bin
      state=present

  - name: Ensure NAS mount path exist
    file:
      path=/mnt/nas
      state=directory
      owner=pi
      group=pi

  - name: Ensure neofetch package is installed
    apt:
      name=neofetch
      state=present

  - name: Ensure mosh package is installed
    apt:
      name=mosh
      state=present

  - name: Ensure qnapi package is installed
    apt:
      name=qnapi
      state=present

  - name: Copy qnapi configuration
    copy:
      src: home/.config/qnapi.ini
      dest: /home/{{ username }}/.config/qnapi.ini
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0644'
    register: result

  - name: Ensure minidlna package is installed
    apt:
      name=minidlna
      state=present

  - name: Copy minidlna configuration
    copy:
      src: etc/minidlna.conf
      dest: /etc/minidlna.conf
      owner: root
      group: root
      mode: '0644'
    register: result

  - name: Restart minidlna service
    service:
      name: minidlna
      state: restarted
    when: result is changed

  - name: Copy login-notify script
    copy:
      src: etc/pam.d/login-notify.sh
      dest: /etc/pam.d/login-notify.sh
      owner: root
      group: root
      mode: '0700'
    register: result

  - name: Enable login notification
    lineinfile:
      path: /etc/pam.d/sshd
      regexp: 'login-notify.sh'
      line: session optional pam_exec.so seteuid /etc/pam.d/login-notify.sh
