---
- hosts: raspberrypi
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
   - rpi_base
- hosts: local_share
  become: yes
  become_method: sudo
  roles:
    - local_share
- hosts: raid
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
    - raid
- hosts: dmz
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
    - dmz
