---
- hosts: raspberrypi
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
   - rpi_base
- hosts: local_share
  roles:
    - role: local_share
      become: yes
      become_method: sudo
- hosts: raid
  roles:
    - role: raid
      become: yes
      become_method: sudo
      gather_facts: no
- hosts: dmz
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
    - role: raid
      become: yes
      become_method: sudo
      gather_facts: no