---
- name: rpi playbook
  hosts: rpi
  become: yes
  become_method: sudo

  tasks:
  - name: Ensure vim package is installed
    apt: name=vim state=present

  - name: Ensure screen package is installed
    apt: name=screen state=present

  - name: Ensure mc package is installed
    apt: name=mc state=present

  - name: Ensure deluged package is installed
    apt: name=deluged state=present

  - name: Ensure autossh package is installed
    apt: name=autossh state=present

  - name: Ensure kodi repo key is imported
    apt_key: url='http://pipplware.pplware.pt/pipplware/key.asc' state=present

  - name: Add kodi repo is added to apt.sources
    apt_repository: repo='deb http://pipplware.pplware.pt/pipplware/dists/jessie/main/binary /' state=present update_cache=true

  - name: Ensure kodi package is installed
    apt: name=kodi state=present

  - name: Ensure kodi autostart is enables
    ini_file: dest=/etc/default/kodi section= option=ENABLED value=1 no_extra_spaces=yes

  - name: Ensure ssh is enabled on port 6969
    lineinfile: dest=/etc/ssh/sshd_config regexp="^Port 6969" line='Port 6969' insertafter="^Port 22"
